#!/bin/bash

rm -rf data.tar.gz control.tar.gz *.ipk *.deb
find . -name '*~' -delete

### Build pi package
rm -rf data.tar.gz control.tar.gz

mkdir -p tmp/var/www/html/iperfspeed
mkdir -p tmp/usr/lib/cgi-bin

cd src/data
cp -R www/* ../../tmp/var/www/html/iperfspeed
cp -R usr ../../tmp/

cd ../../tmp
COPYFILE_DISABLE=1 tar cfz ../data.tar.gz `find . -type f | grep -v DS_Store`

cd ../src/control
COPYFILE_DISABLE=1 tar cfz ../../control.tar.gz .
cd ../..
COPYFILE_DISABLE=1 ar r iperfspeed_0.1_all.deb debian-binary control.tar.gz data.tar.gz
rm -rf tmp
